const tokenEndpoint = {NA:'https://api.amazon.com/auth/o2/token',EU:'https://api.amazon.co.uk/auth/o2/token',FE:'https://api.amazon.co.jp/auth/o2/token'};
export function amazonConfigured(){return !!(process.env.AMAZON_CREATOR_CLIENT_ID&&process.env.AMAZON_CREATOR_CLIENT_SECRET&&process.env.AMAZON_PARTNER_TAG)}
async function token(){const r=await fetch(tokenEndpoint[process.env.AMAZON_REGION||'NA'],{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({grant_type:'client_credentials',client_id:process.env.AMAZON_CREATOR_CLIENT_ID,client_secret:process.env.AMAZON_CREATOR_CLIENT_SECRET,scope:'creatorsapi::default'}),cache:'no-store'});if(!r.ok)throw new Error('Amazon auth failed');return (await r.json()).access_token}
export async function searchAmazon(keywords='trending products'){
 const access=await token(); const marketplace=process.env.AMAZON_MARKETPLACE||'www.amazon.com';
 const r=await fetch('https://creatorsapi.amazon/catalog/v1/searchItems',{method:'POST',headers:{authorization:`Bearer ${access}`,'content-type':'application/json','x-marketplace':marketplace},body:JSON.stringify({keywords,marketplace,partnerTag:process.env.AMAZON_PARTNER_TAG,itemCount:10,resources:['images.primary.large','itemInfo.title','offersV2.listings.price']}),cache:'no-store'});
 if(!r.ok) throw new Error(`Amazon catalog ${r.status}`); return r.json();
}
export function normalizeAmazon(payload){const items=payload?.searchResult?.items||payload?.items||[];return items.map((x,i)=>({id:x.asin||`amazon-${i}`,asin:x.asin,title:x.itemInfo?.title?.displayValue||x.title||'Amazon find',category:'Trending',price:x.offersV2?.listings?.[0]?.price?.money?.amount||null,trendScore:Math.max(70,98-i*3),image:x.images?.primary?.large?.url||'',url:x.detailPageURL||x.detailPageUrl||'#',reason:'Selected from the current Amazon catalog refresh'}))}
